version: "2"
services:
  borderguru-order-api:
    container_name: borderguru-order-api
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.6
    volumes:
      - ./db:/data/files
    ports:
      - "27017:27017"